# Generated by Django 6.0.5 on 2026-05-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('prediction', models.IntegerField()),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
